### ISSUE TITLE
TPP Zone not found for deep folder structure

### ISSUE THREAD

**Issue by jtcarnes** [Venafi/terraform-provider-venafi#41] opened 2021-02-24 15:49 UTC
**PROBLEM SUMMARY**
When looking to upgrade to 0.11.1, we encountered `zone not found` everywhere. We have rather deep folders so this might be the issue. 0.10.2 works.

**STEPS TO REPRODUCE**
provider "venafi" {
url = "my-companies-tpp"
zone = "\\VED\\Policy\\Certificates\\Internal\\Folder With Spaces\\final.zone.folder"
}

**EXPECTED RESULTS**
Zones that are deep in the folder structure to be found

**ACTUAL RESULTS**
Error: could not read zone configuration: vcert error: your data contains problems: zone not found

**COMMENTS/WORKAROUNDS**
Version 0.10.2 works, so it's most likely a problem introduced in 0.11

**Comment by tr1ck3r** [comment] 2021-02-24 16:14
@jtcarnes we believe this issue was addressed in `v0.11.1` (the defect was introduced in `v0.11.0`) can you please verify that you tested with `v0.11.1` and not `v0.11.0`?

**Comment by jtcarnes** [comment] 2021-02-24 17:24
I can confirm that it's a problem for v0.11.1.

**Comment by tr1ck3r** [comment] 2021-02-24 18:07
Thank you for confirming @jtcarnes.  The issue appears to be not that the folder structure is deep but that you are using the "long form" for the zone.  Definitely a 🐛 that we'll work on fixing but, fortunately, there is a straightforward workaround that is also arguably better.  When you specify the `zone`, instead of _"\VED\Policy\Certificates\Internal\Folder With Spaces\final.zone.folder"_ you should specify _"Certificates\Internal\Folder With Spaces\final.zone.folder"_ and everything should work properly with `v0.11.1`.

**Comment by rvelaVenafi** [comment] 2021-02-24 22:23
The issue is related to a method that removes double forward slashes "\\" from the zone string before passing it to vcert sdk.
This method did not take into consideration the case when the full zone path is passed (\\VED\\Policy\\One\\Two) and removed the leading forward slash from the string, resulting in:
VED\Policy\One\Two
The fix has this case in consideration and appends the forward slash when required.
 
 The fix will be available in next release 0.11.2

**Closed as completed by rvelaVenafi** 2021-02-24 22:23 UTC
Labels: bug
