### ISSUE TITLE
Error on applying plan

### ISSUE THREAD

**Issue by zerolaser** [Venafi/terraform-provider-venafi#13] opened 2019-03-01 07:52 UTC
Here's my terraform code.
Using the latest version pre-release version v0.4 and terraform version 0.11.11
```
provider "venafi" {
    url          = "${var.venafi_url}"
    tpp_username = "${var.user}"
    tpp_password = "${var.pass}"
}

resource "venafi_certificate" "webserver" {
    common_name = "${var.cname}"
}
```
while running  **terraform apply**

```
Error: Error applying plan:
1 error(s) occurred:

* venafi_certificate.webserver: 1 error(s) occurred:

* venafi_certificate.webserver: Unexpected status code on TPP Certificate Request. 
Status: 400 Bad Request, check Error in response for details.. Body: {"Error":"PolicyDN: \"\\VED\\Policy\\Default\" does not exist or you do not have sufficient rights to the object.\u000d\u000aNeed a certificate authority 
(CADN).\u000d\u000a"}: {"Error":"PolicyDN: \"\\VED\\Policy\\Default\" does not exist or you 
do not have sufficient rights to the object.\u000d\u000aNeed a certificate authority (CADN).\u000d\u000a"}

```

running in debug mode shows the following error.

```
2019/02/28 23:39:15 [TRACE] root: eval: *terraform.EvalWriteState
2019/02/28 23:39:15 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/02/28 23:39:15 [TRACE] root: eval: *terraform.EvalIf
2019/02/28 23:39:15 [TRACE] root: eval: *terraform.EvalWriteState
2019/02/28 23:39:15 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/02/28 23:39:15 [TRACE] root: eval: *terraform.EvalApplyPost
2019/02/28 23:39:15 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* venafi_certificate.webserver: Unexpected status code on TPP Certificate Request. Status: 500 Internal 
Server Error. Body: The page cannot be displayed because an internal server error has occurred.: The 
page cannot be displayed because an internal server error has occurred.
2019/02/28 23:39:15 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* venafi_certificate.webserver: Unexpected status code on TPP Certificate Request. Status: 500 Internal 
Server Error. Body: The page cannot be displayed because an internal server error has occurred.: The 
page cannot be displayed because an internal server error has occurred.
2019/02/28 23:39:15 [TRACE] [walkApply] Exiting eval tree: venafi_certificate.webserver
2019/02/28 23:39:15 [TRACE] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2019/02/28 23:39:15 [TRACE] dag/walk: upstream errored, not walking "provider.venafi (close)"
2019/02/28 23:39:15 [TRACE] dag/walk: upstream errored, not walking "root"
2019/02/28 23:39:15 [TRACE] Preserving existing state lineage "e11b4ede-55a4-cb72-0e6d-076febe798d2"
2019/02/28 23:39:15 [TRACE] Preserving existing state lineage "e11b4ede-55a4-cb72-0e6d-076febe798d2"
2019/02/28 23:39:15 [TRACE] Preserving existing state lineage "e11b4ede-55a4-cb72-0e6d-076febe798d2"
2019/02/28 23:39:15 [TRACE] Preserving existing state lineage "e11b4ede-55a4-cb72-0e6d-076febe798d2"

2019/02/28 23:39:15 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error applying plan:

1 error(s) occurred:

* venafi_certificate.webserver: 1 error(s) occurred:

2019-02-28T23:39:15.522-0800 [DEBUG] plugin.terraform-provider-venafi: 2019/02/28 23:39:15 [ERR] plugin: plugin server: accept unix /var/folders/xn/mcw6ky311sx1nqsrj8ccbhbm0000gn/T/plugin351282435: use of closed network connection
* venafi_certificate.webserver: Unexpected status code on TPP Certificate Request. Status: 500 Internal Server Error. Body: The page cannot be displayed because an internal server error has occurred.: The page cannot be displayed because an internal server error has occurred.

```
Unsure what error message exactly says. 

Generally we use venaficli ruby gem and create/renew certs using the venaficli
Our command looks like this. 
```
venaficli  makesingle -c venafi.yml --cn  test.company.com --ca internal 
``` 
where venafi.yml contains TPP_USER and TPP_PASSWORD. 

venaficli has commands like makesingle, renew, makebatch, fetch
can you update the README file on how to achieve some of these features ? also how do we specify cert authority (--ca option) ?

**Comment by mr-tron** [comment] 2019-03-01 08:34
You forgot to specify `zone=<your_zone_name>`, so plugin use `Default` zone which is not configured in your TPP.

**Comment by arykalin** [comment] 2019-03-01 08:40
Hi @zerolaser regarding CA option, terrafrom integration is based on VCert SDK which doesn't support CADN option. Please see issue https://github.com/Venafi/vcert/issues/6

**Comment by zerolaser** [comment] 2019-03-01 22:23
Thanks @mr-tron . adding that I was able to create it.

**Comment by zerolaser** [comment] 2019-03-01 22:28
On a separate note. Not sure if renew is part of VCert SDK or you guys planning on adding it ?

**Comment by arykalin** [comment] 2019-03-02 13:06
@zerolaser renew is already implemented in VCert SDK, but not in the terraform provider. However we plan to implement it soon.

**Comment by zerolaser** [comment] 2019-03-04 04:34
thanks @arykalin. Looking forward to it. 
Just would like to know, what happens if the cert is expired now?
It checks if that cert is already present, if it is presented then it doesn't show any terraform changes ?

**Comment by tr1ck3r** [comment] 2019-03-04 18:17
@zerolaser thank you for bringing this issue to our attention.  Our Terraform provider was originally designed solely as a method for requesting a single certificate.  Basically apply, show, and destroy... and repeat to get another certificate.  We see that there is value in a longer lived plan which means updating our Terraform provider to take advantage of the existing VCert SDK renewal capabilities as @arykalin mentioned we will be working on soon.

**Comment by zerolaser** [comment] 2019-03-04 22:49
@tr1ck3r we use venafi a lot and we would love to this venafi provider official.

**Comment by zerolaser** [comment] 2019-03-04 22:54
@arykalin I was getting this error when I do `terraform destroy` and re-apply. 
As soon as I create the venafi cert, i'm passing the key,chain and certificate to aws certificate manager but i'm getting this following error.

* aws_acm_certificate.cert: Error importing certificate: ValidationException: Key provided does not match the certificate.

I tried manually uploading the cert its saying key doesn't match the certificate.

Can you explain me what happens when I do terraform destroy on venafi_certificate ?
when i do *terraform destroy* I dont see the cert getting deleted or retire or revoked on my venafi website.
may be it's a permissions issue ? but terraform dint error out anything.

**Comment by zerolaser** [comment] 2019-03-04 23:07
let me know if i should start the above comment as a new issue closing this one out.

**Comment by zerolaser** [comment] 2019-03-04 23:19
Also I forgot to mention. Adding the email notification to send out the alerts when the cert nearing to expiration.

**Comment by arykalin** [comment] 2019-03-05 13:30
@zerolaser regarding key issue, please look here https://github.com/Venafi/terraform-provider-venafi/issues/15
Hope it is fixed in the latest release (0.6.0)

**Comment by zerolaser** [comment] 2019-03-06 00:35
thanks @arykalin That fixed my issue. but it ended up creating a new one. The **private_key_pem** generated is in rsa format and needs to be convert it to some sort of PEM–encoded format AWS ACM to accept it. 
I tried writing a null_resource to do run openssl commands but I have to write multiple null_resources.  first to store the private_key and passphrase to  respective files(as openssl doesn't accept in line content of pem and passphrase). then I need to pass-in those to the openssl command with these files and finally get the converted format of pem and finally pass this private key to acm resource.  

The older version (v0.4) of venafi provider was directly converting the private key to the respective format. I had no issues in passing the private key directly to the acm resource.

I was wondering if you could have a new property of converted private key to the respective pem format or may be another resource(data resource ?) that would do the work i mentioned above ? It would make the work a lot simpler.

**Comment by tr1ck3r** [comment] 2019-03-06 05:42
@zerolaser the only difference I'm seeing with the **private_key_pem** behavior in v0.6.0 is that it is honoring the **key_password** parameter and encrypting the private key (i.e. we fixed a bug).  To have your private key output with no encryption (same as v0.4.0) you'd just need to omit the **key_password** parameter.

**Comment by zerolaser** [comment] 2019-03-06 07:03
@tr1ck3r I tried recreating it omitting the password and I was able to successfully create the cert via venafi and pass it to acm.
but destroying and re-applying it threw the same error.

```
Error: Error applying plan:

1 error(s) occurred:

* aws_acm_certificate.cert: 1 error(s) occurred:

* aws_acm_certificate.cert: Error importing certificate: ValidationException: Key provided does not match the certificate.
	status code: 400, request id: 600333fa-3fd4-11e9-bc6f-97bfea8ace9d

```

Secondly, We do not want to omit the key_password parameter. after creating the venafi cert on console or using venafi, we download the cert and convert the p12 file to private key using the following openssl command. 
```
openssl pkcs12 -in <common_name>.p12 -nocerts -nodes -out <common_name>.key -passin pass:$pwd -passout pass:$pwd
```

**Comment by arykalin** [comment] 2019-03-06 07:57
Hi @zerolaser  
about first issue, could you show terraform plan you trying to apply? Maybe the problem is that you're trying to import certificate with encrypted key file and aws_acm can't read it?

about second issue, could you please clarify,, you want terraform provider to be able to provide certificates in pkcs12 format? For now we're providing PEM formatted files, in case of key_password parameter RSA key will be in encrypted format and have to be unencrypted.

**Comment by zerolaser** [comment] 2019-03-06 08:18
@arykalin On first Issue, it was happening even when the key_password was omitted. Not sure what I can and cant post here. i'll email to opensource@venafi.com.
**Steps to replicate**. apply then destroy and re-apply it.  venafi resource will created but acm will complain key doesn't match cert.
`terraform destroy` doesn't delete the cert from our venafi site nor revokes or retires it. but `terraform apply` will generate a new private key each time.


On the second Issue, I don't want the provider to output pkcs12 format (I told you how we do it with cli,  decrypt it with openssl by passing in passphrase and finally upload it to acm). All I want is the venafi provider to have capabilities to decrypt it and pass in the decrypted key to acm as acm doesn't know what to do with the encrypted private key.

**Comment by zerolaser** [comment] 2019-03-06 19:12
@arykalin Have received my email ?

**Comment by arykalin** [comment] 2019-03-06 20:52
@zerolaser yes, I have, sorry for the late reply. I'll close this issue, because current problem is similar to the
[the https://github.com/Venafi/terraform-provider-venafi/issues/15](issue 15)
About you second request, yes, there is a point in it, could you open another issue here with feature request in it?

**Closed by arykalin** 2019-03-06 20:52 UTC
